# MODULO: root
# .. ............................................................... mkdocs ..
# Configuración de sitio web para documentación estática.


site_name: Tasks-CLI Documentación

dev_addr: 127.0.0.1:8001

repo_url: https://github.com/Gustavo9481/Tasks-cli.git

theme:
  logo: /images/logo.svg
  language: es
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    code: JetBrainsMono Nerd Font

  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - content.code.copy

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('.')
          options:
            docstring_style: google

nav:
  - 'Inicio': index.md
  - 'Guía de Usuario': guia_usuario.md
  - 'Guía de Desarrollo': guia_desarrollo.md
  - 'Arquitectura': arquitectura.md
  - 'Referencia de la API':
    - 'Controladores':
      - 'Interface': referencia_api/controllers/interface.md
      - 'Pantallas': referencia_api/controllers/screens.md
    - 'Modelos':
      - 'Task': referencia_api/models/model_task.md
    - 'Repositorios':
      - 'Repository DB': referencia_api/repositories/repository_db.md
      - 'Connection Manager': referencia_api/repositories/connection_manager.md
      - 'Querys': referencia_api/repositories/querys.md
    - 'Servicios':
      - 'Task Service': referencia_api/services/task_service.md
    - 'Pruebas':
      - 'Pruebas del Modelo': referencia_api/tests/models_tests/test_model_task.md
      - 'Pruebas del Repositorio': referencia_api/tests/repositories_tests/test_repository_db.md
