# MODULO: config
# .. ............................................................. settings ..
# Archivo de configuración para la aplicación Tasks-CLI.
# Contiene los valores estáticos de colores e íconos para la interfaz.
# Para configurar un aspecto personalizado, los cambios deben hacerse en éste
# archivo.

# .. .................................... Configuración de la base de datos ..
# almacena el nombre de la base de datos a usar.
database_name = ""
# Para configurar bases de datos de prueba solo se debe definir un nombre en la 
# variable, ejemplo: database_name = "tests.db".

# .. ......................................... Configuración de la interfaz ..
# Colores e íconos de la interfaz.
[ui.colors]
red = "#FF7A93"
blue = "#7AA2F7"
green = "#B9F27C"
orange = "#FF9E64"

[ui.icons]
pendiente = " "
en_proceso = " "
completada = " "
baja = " "
media = " "
alta = " "
nota = " "
